== to read tonight:
phonon dispersion measurement w/ neutron scattering? https://journals.aps.org/prb/pdf/10.1103/PhysRevB.60.284


Modeling matter
---------------
* electron/hole mobility in Ge and Si crystals
* creation of free charges in Ge and Si crystals
  -- electron-phonon coupling
  -- recombination effects
  

Modeling matter: phonon-charge partitioning of energy
-----------------------------------------------------
Nader's paper says, "We are as-
suming that at these low energies the sudden creation of
lattice defects provides enough local perturbation in the
electronic band structure to create an electron-hole pair
excitation."

Can we model this?  Can we measure this (does the Lindhard curve measure this)?  Sure, electron-hole recombination makes this messy.  Is there a simple way to start, though?  It'd be nice to compare to data and be able to put a limit on the size of additional effects.
 
 * http://cmt.dur.ac.uk/sjc/thesis_prt/node56.html
 * measuring phonon-exciton coupling with Raman spectroscopy: http://pubs.acs.org/doi/abs/10.1021/acs.jpclett.6b02944
 * 2D electron-phonon coupling: https://journals.aps.org/prb/pdf/10.1103/PhysRevB.88.121403
 * tunneling, phonon spectra: http://onlinelibrary.wiley.com/doi/10.1002/qua.560020734/abstract (M. Dresselhaus!)


Modeling matter: charge trapping
--------------------------------
Do we really understand charge trapping?  I don't.  Can we improve our model?  How can we validate it?

Wendi is working on predicting ??.  The Raman spectrum would also be useful.
 * Raman spectroscopy of Ge: https://journals.aps.org/pr/pdf/10.1103/PhysRev.155.712
 * more Raman spect of Ge: http://iopscience.iop.org/article/10.1088/0268-1242/31/10/105012/meta;jsessionid=DB1AED6ED6096034FB77189E1168B1C7.ip-10-40-1-105
 * experimental how-to for measuring Raman: http://www.sciencedirect.com/science/article/pii/S0038109811000391?via%3Dihub#f000015

Data: mobility/lifetime as a function of temperature.


Modeling matter: softened Compton step
--------------------------------------
DAMIC sees a softened Compton step when looking at Compton scattering (https://arxiv.org/pdf/1706.06053.pdf) but not when looking at photoelectric-effect data (https://confluence.slac.stanford.edu/display/CDMS/Science+Meetings, Karthik).  The obvious physical difference is Compton: highish energy gamma in final state, photoelectric: no gamma in final state.

Can we use DFT to understand why these scatters would look different?  Or, why we don't see the full energy for some Compton scatters?  If people use VASP to simulate lasers on germanium, can we use VASP to simulate this?  (Probably not directly comparable, Amy!  Lasers are steady-state while a single gamma is not.)


Modeling matter: direction dependence
-------------------------------------
What do we expect our detectors to measure for a delta-function energy transfer E?  

Well, what *direction* was that kick?  Energy transfers in different directions will partition that energy deposition between phonons and electrons differently.  Predict this, and provide code that generates the spectrum we expect to see in our HV and iZIP detectors for a given background.

Damn, Nader already did the majority of this work: https://arxiv.org/pdf/1703.05371.pdf.  Can we measure this?  Is this effect large enough to explain the softened shoulder DAMIC sees on the Compton step?


Modeling matter: atomic-scale Lindhard
--------------------------------------
We'd all love an atomic-scale theory of how energy deposition is partitioned into electron and phonon systems - but it's hard because the unit cell you'd have to use for DFT is way beyond what computers can do in a year.

Some of the folks at LBNL and also England are making inroads by stitching together DFT methods with ... other, faster methods.  We should work with them, apply the methods to our detectors, and compare to measured calibration data!


Modeling matter: first steps
----------------------------
Historically, when we imagine a dark matter particle interacting in our detector, we pretend like the nucleus is a free particle floating in a vacuum.  This is a really good approximation if the energy transfer is large (say, 1 keV) because the scale of atomic binding energy is on the order of 10 eV.  But the dark matter community wants more sensitive experiments and drives hard to look at smaller and smaller energy transfers (CDMS recently published a paper that looked at energy transfers as small as 56 eV).  And it turns out we don't really understand energy transfer at these low-energy scales.

So that's exciting!

As it turns out, chemists have been interested in understanding how atoms move for a very long time - protein folding is a classic example.  They combine an accurate description of the electric field of an atom with F = ma (or sometimes the quantum mechanical version of that) and ... watch how the atoms move.  Which is exactly what we'd like to do.

The specific work I have in mind here is to adapt an instructional analysis on water to use the open-source NAMD code.  The downside is that this isn't immediately related to the CDMS dark matter search.  But it's a nice, finite project that gives you a chance to use electrostatics, electrodynamics, and quantum mechanics together to predict some properties of water.  And if you enjoy this work, an obvious second project is to do something similar but for germanium.


Signal to noise
---------------
When something interacts in our detector, it's only useful to us if we know about it.  So we set our detector up with sensors, and then the detector can tell us when something happens.

Then our job becomes one of translation: using only the signals from the detector, we need to determine what physics happened.

We have good ways of doing this, but I wonder if we could do even better by using all the signals from a detector, simulatneously.  (Right now we use them seperately.)  Specifically, I wonder if non-negative matrix factorization methods might give us a better signal-to-noise ratio.

This is a fun, highly math-oriented project that would involve lots of looking at original data, comparing to current algorithms, and thinking about the maximum amount of information we can get out of our signals.

* analyzing electrical activity measurements from several muscles: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5593271/
* reducing wind noise in seismology data!  http://www.sciencedirect.com/science/article/pii/S0016716914714916#f0005 and https://gsw.silverchair-cdn.com/gsw/Content_public/Journal/srl/85/5/10.1785_0220130142/4/1056.pdf?Expires=1514004100&Signature=JilBiseCRY5YYQz7valh4172a5oKo4gJhk4GyjIu-XalWJXatDIlWR4kGKXEsW8Dmpff9aUHdzzVMacGDa0KRRx3rYmCPpdp27VCl~uqV~II19lYIiM18qG4Wg2HTlGnf7gKTi4FFJnKj5iaOSA7D6u~L1cDX1CRkQn38CSzJRpOZQWAOL2BVY4p1lSkD8URfdjLES8al5en~i4-jCE2srh1dHciPnMjWE5~1~TvC3s~d2xXqOrRou3EEaMxoAeKdIjX5LDiSSaRMKJj1r-UErHpo-MwV6AMGOtjPe4RBa9d~XPJpUi1KPIUEaooFIbsTDdp4Y0vKMYNx5TfnHCp5A__&Key-Pair-Id=APKAIUCZBIA4LVPAVW3Q
* estimating distance with microphone arrays: http://citeseerx.ist.psu.edu/viewdoc/download;jsessionid=CDB002530843AE9DA3B1B3B1943906D0?doi=10.1.1.700.2013&rep=rep1&type=pdf
* position reconstruction of brain signals with sensor arrays (!) https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5579488/
* multi-channel, blind source separation: https://dl.acm.org/citation.cfm?id=2992841
* template extraction: http://audition.ens.fr/adc/pdf/2008_NIPS_LeRoux_Parra.pdf

Was that two hits or one? (Parker Pyle currently working on this)
-----------------------------------------------------------------
Surprisingly, calibrating the energy scale of our detectors is a real challenge.  Lots of standard calibration sources emit gammas or betas and these predominantly interact with the *electrons* in our detectors.  But we expect dark matter to overwhelmingly interact with the *nuclei* in our detectors.  

So ... what can we use to calibrate energy transfers to nuclei in our detectors?  Neutrons!

Except that - unlike gammas - it's hard to get neutrons that are all exactly the same energy.  So then we tie ourselves into knots trying to figure out how to use neutrons to calibrate despite their uncooperative nature.

I've actually got several projects related to this, but the one that immediately comes to mind is looking at some existing data to see if we can find a way to identify events where a neutron interacted in a detector many times, rather than only once.  (Low energy neutrons have a path length on the order of cm and tend to interact several times in our detectors, significanly complicating calibration analysis.)

This analysis is likely to be really fun at first - you'd spend a lot of time looking directly at detector signals and thinking about the physics that creates them.  But identifying events with multiple interactions is not gauranteed to be possible.  So the result of this analysis could well be "it would be super awesome to be able to distinguish multiple-interaction events but I have conclusively shown that this is not possible with CDMS detectors".  

If calibration sounds interesting to you but you're not keen on bitter disappointment, let me know and I can fill you in on some alternative calibration projects that, while not as signal-oriented as this one, aren't null-result territory.

Data without pain
-----------------
Currently it's a pretty tough process to simply look at CDMS data - both raw and processed.  Can we make a python library that makes it easy to load raw and processed data?  I'm imagining something like a raw-data server that, given an HTTP request, will return event data (or an array of event data).  BatViewer already essentially does this, it's just that it needs to be invoked on the command line and the thing it returns is a file with ROOT histograms.  We'd need to add an output format option (JSON/BSON/whatever as long as there are plenty of python libraries that can decode it) and set up a server to invoke the executable and return the data produced.  And then we'd want to write a python library that's a wrapper for the HTTP requests.  


Miscellany
----------
* build a small cosmic-ray detector!
* help fix unnecessary exclusion: make our detector-control software accessible to people with low or no vision
* solve a problem that plagues the entire physics community: develop a prototype data reader and writer that needs only a user-supplied description of the data to read and write files
* how we process the data now is fine but what if we could do it better!?: measure the speed of the algorithms we use to process CDMS data; adapt them for use on a GPU
* why so slow, mhttpd: one of the core pieces of our DAQ software is sometimes incredibly slow.  Find out why, and fix it.
* Make it easier to process CDMS data: Develop a Nix expression that will install the version of ROOT needed by CDMS software.    
* write tests for the CDMS optimal-interval code/do sanity checks

* Want to be able to write MIDAS-format data files independent of the MIDAS DAQ  
** Could update and try for a pull request: midasio.cxx, midasio.h in rootana/libMidasInterface/ (https://bitbucket.org/tmidas/rootana/src/bd5c53afa728a4c838095d73f8c53af29d50616d/libMidasInterface/?at=master).  However, the DAQ group consensus is that we will implement file reading/writing in the dataio library.  Ben Smith is working on this.
** cdmsbats' responsibility to map dataio structure to its data structure
** need a map from TES channel name to channel number.  Anthony: this map is used primarily in analysis and will likely stay in cdmsbats.  Matt: I need to think about this because the DMC uses channel names, not numbers.  
** also need to consider adding a write_odb() function for the dataio library.  Ben Smith is looking into this.
